### PR TITLE
[R] fix (x):fix bug of shared models with subfields in blueprint

### LINKED ISSUE #168: BluePrint - Obscure error when generating a type of sharedModel
When trying to generate the following sharedModel:

```
export const I18NField = sharedModel({
  id: "I18NField",

  fields: [
    field.object("values", {
      subfields: [
        field.enum("lang", {
          enumValues: ["EN", "DE"],
        }),
        field.string("text"),
      ],

      isArray: true,
    }),
  ],
});
```

The error:
```
We detected multiple fields in "Users" collection with field: "createdAt". The last one added was kept.
Starting generating project:  app
➤ Backend microservice already exists. (skipping)
✓ Created collection, model and GraphQL entity for: Users
Something went wrong with the generation:
TypeError: Cannot read property 'entityName' of undefined
    at Function.fieldToGenericField (app/node_modules/@bluelibs/x/src/studio/bridge/XBridge.ts:209:43)
    at app/node_modules/@bluelibs/x/src/studio/StudioWriter.ts:622:39
    at Array.forEach (<anonymous>)
    at StudioWriter.createSharedModels (app/node_modules/@bluelibs/x/src/studio/StudioWriter.ts:621:20)
    at StudioWriter.write (app/node_modules/@bluelibs/x/src/studio/StudioWriter.ts:128:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async generateProject (app/node_modules/@bluelibs/x/src/studio/generateProject.ts:32:5)
```

If I remove the `subfields`, it works.

### PR DESCRIPTION
**Pull request by y-moufakkr**
close #168 
the issue is fixed, but need to fix another UI issue, there s no input fields for array of subfields in shared model

### CODE REVIEW

File: packages/x/src/studio/models/Field.ts [hunk 1]
```diff
@@ -119,6 +119,12 @@ export class Field extends BaseModel<Field> {
    */
   collection: Collection;
 
+  /**
+   * The sharedmodel it belongs to. .
+   * @cleanable
+   */
+  sharedCollection?: SharedModel;
```
Comment (theodorDiaconu) [inline packages/x/src/studio/models/Field.ts:126]: The name here is kinda confusing since we have "Collections" behave different from models, let's do a getSharedModel() which does this check for us and retrieves us the SharedModel, we can always get it dynamically.

**Review by theodorDiaconu — CHANGES_REQUESTED** [review]
