### PR TITLE
fix i18 and x-ui-admin bundle:default locale and date format

### LINKED ISSUE #238: Date format do not match the defaultLocale
**Describe the bug**
When we force the `defaultLocale` (in `/microservices/admin/src/startup/kernel.ts`), this is applied only to language and not to date's format.

**To Reproduce**
1. Set `defaultLocale` to French (e.g.) in `/microservices/admin/src/startup/kernel.ts` :
```
i18n: {
  defaultLocale: "fr",
 },
```
2. Open a List or a Viewer page that contain a date item (e.g. : createdAt)
We could see that the date format still 'en' (MM/DD/YYY) if your browser and / computer is set to English.

**Expected behavior**
Date format should match the `defaultLocale` is it's set.
If `defaultLocale: "fr"` : date format = DD/MM/YYY and NOT MM/DD/YYY

**Suggested Solution**
In [this code line](https://github.com/bluelibs/bluelibs/blob/aa0cfe646e320f5e6614dd1d57b4f790baf765f7/packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx#L63) : `value = props.value.toLocaleDateString();` 
should be : 
```
value = !!kernel.bundles[0].getConfig().i18n.defaultLocale 
? props.value.toLocaleDateString(kernel.bundles[0].getConfig().i18n.defaultLocale) 
: props.value.toLocaleDateString();
```

### PR DESCRIPTION
**Pull request by y-moufakkr**
make the date format in ui-admin follow the current polyglot format
fixes #238

### CODE REVIEW

File: packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx [hunk 1]
```diff
@@ -59,11 +59,12 @@ export function AdminListItemRenderer(props: AdminListItemRendererProps) {
   }
 
   if (props.type === "date") {
+    const local = container.get(I18NService)?.getCurrentPolyglot();
```
Comment (theodorDiaconu) [inline packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx:62]: why the ?, could you also do it like const i18n = use(I18NService); on top?

**Review by theodorDiaconu — CHANGES_REQUESTED** [review]
Check comments.
