### PR TITLE
[R] fix (smart,x-ui-react-bundle): handle error use smart before kernel init

### LINKED ISSUE #191: useSmart- `Model is null` if kernel is not initialized
Basically, this is the error that appears when we try to use a smart (e.g. the guardian) before the kernel is initialized.

I know you are not supposed to do this, but I think we should handle the error, somehow.

image

### PR DESCRIPTION
**Pull request by y-moufakkr**
closes #191 
if this solution is ok, I need to do it on next-ui too

### CODE REVIEW

File: packages/smart/src/hooks.ts [hunk 1]
```diff
@@ -121,6 +121,13 @@ export const useSmart = <T extends Smart>(
   },
   options?: UseSmartOptions
 ): T => {
+  if (!window.sessionStorage.getItem("isKernelInitialized")) {
+    setTimeout(() => {
```
Comment (theodorDiaconu) [inline packages/smart/src/hooks.ts:125]: I remember we discussed about this change, jsut to check via container. Not sure where we pushed it?
