### PR TITLE
[R] feat(x-ui-admin): try catch on admin listitemrendering

### LINKED ISSUE #42: (x-ui-admin) AdminListItemRenderer: When a field fails to render, the error is propagated to the top PageContent.
We should have an error boundary at item rendition level, or devise a strategy of try { } catch {} within the component that renders: `AdminListItemRenderer`

### PR DESCRIPTION
**Pull request by y-moufakkr**
closes #42

### CODE REVIEW

File: packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx [hunk 1]
```diff
@@ -47,97 +47,104 @@ export function DownloadButton({ name, downloadUrl }) {
...
-  }
-
-  if (value === undefined || value === null) {
-    return emptyValue;
+    if (value === undefined || value === null) {
+      return emptyValue;
+    }
+    return value;
+  } catch (err) {
+    console.error(err);
```
Comment (theodorDiaconu) [inline packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx:147]: Please just use <ErrorBoundary> from components.

Comment (theodorDiaconu) [inline packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx:147]: Please just use <ErrorBoundary> from components.
