### PR TITLE
fix x-ui-collections-bundle: make updatebodyfix skip the mongo operators

### LINKED ISSUE #231: X-UI-Collections-Bundle - "Update" doesn't work anymore
On a freshly-generated project, you can go to the admin panel and try to update a document from any collection. You'll receive the following error:

```
GraphQLError: Syntax Error: Expected Name, found "$".
    at syntaxError (syntaxError.mjs:8:1)
    at Parser.expectToken (parser.mjs:1397:22)
    at Parser.parseName (parser.mjs:82:1)
    at Parser.parseField (parser.mjs:279:1)
    at Parser.parseSelection (parser.mjs:268:38)
    at Parser.many (parser.mjs:1507:1)
    at Parser.parseSelectionSet (parser.mjs:255:1)
    at Parser.parseField (parser.mjs:296:48)
    at Parser.parseSelection (parser.mjs:268:38)
    at Parser.many (parser.mjs:1507:1)
```

The request is not sent, meaning it's a problem when formatting the query on the front-end.

### PR DESCRIPTION
**Pull request by y-moufakkr**
and use the fields used inside those operators instead 
fixes #231 && #213

### CODE REVIEW

File: packages/x-ui-collections-bundle/src/graphql/utils/toQueryBody.ts [hunk 1]
```diff
@@ -29,11 +29,17 @@ export const toQueryBody = (dict) => {
   if (isObjectPrototype(dict)) {
     return Object.entries(dict).reduce((acc, [key, value]) => {
       if (value !== undefined) {
-        acc[key] = isObjectPrototype(value)
+        const query = isObjectPrototype(value)
           ? toQueryBody(value)
           : isArrayOfObjects(value)
           ? arrayToQueryBody(value as any[])
           : 1;
+        //not sure if we have to define the mongo operators with "$" or actually define an array of operations: ["$set","$inc"...]
```
Comment (theodorDiaconu) [inline packages/x-ui-collections-bundle/src/graphql/utils/toQueryBody.ts:37]: starting with $ is safe I would say.
