### PR TITLE
fix x and x-ui-admin: allow representedBy to be nested

### LINKED ISSUE #169: Blueprint Collections - allow "representedBy" to be nested
For example, if I have a collection `Products` with a field `name` which is an object, and I have another collection `EndUsers` which has a relation to `Products`, I want to be able to represents `Products` in UI via `name.text`, i.e.:

`representedBy: "name.text"`

The workaround for this, at the moment, is to create a reduced field, and use that one.

### PR DESCRIPTION
**Pull request by y-moufakkr**
fixed the [https://github.com/bluelibs/bluelibs/issues/169](issue 169),
allowing the representedBy to be nested, example: representedBy ='profile.job.jobTitle'
fixes #169

### CODE REVIEW

File: packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx [hunk 1]
```diff
@@ -121,7 +121,11 @@ export function AdminListItemRenderer(props: AdminListItemRendererProps) {
 
     value = (
       <Link to={props.relation.path}>
-        <Tag>{props.value[props.relation.dataIndex]}</Tag>
+        <Tag>
+          {props.relation.dataIndex
```
Comment (theodorDiaconu) [inline packages/x-ui-admin/src/react/components/AdminListItemRenderer.tsx:125]: you've used this in many places. Recommend you use: https://www.npmjs.com/package/lodash.get

File: packages/x/src/studio/models/App.ts [hunk 2]
```diff
@@ -22,10 +22,22 @@ export class BaseModel<T = null> {
...
 
-    field: (collectionId: string, id: string): Field => {
+    field: (collectionId: string, id: string): Field | Field[] => {
       const collection = this.find.collection(collectionId);
-      const f = collection.fields.find((f) => f.id === id);
-
+      let fieldsPath = id.split(".");
+
+      let f = collection.fields.find((f) => f.id === fieldsPath[0]);
+      let arrayFields = [f];
```
Comment (theodorDiaconu) [inline packages/x/src/studio/models/App.ts:30]: abstract this into a function and explain what it does.

File: packages/x/src/studio/models/Collection.ts [hunk 3]
```diff
@@ -47,7 +47,7 @@ export class Collection extends BaseModel<Collection> {
    * When other collections relate to this, we need a toString() version of this collection document.
    * This can be a field reducer or an actual field, like "fullName" for `User`, or "name" for `Project`
    */
-  representedBy: Resolvable<Field>;
+  representedBy: Resolvable<Field | Field[]>;
```
Comment (theodorDiaconu) [inline packages/x/src/studio/models/Collection.ts:50]: why would the fields be an array of Field?

Comment (y-moufakkr) [reply packages/x/src/studio/models/Collection.ts:50]: its array represent the path to the nested field
